# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    - gocyclo       # Cyclomatic complexity
    - goconst       # Find repeated strings
    - misspell      # Fix commonly misspelled words
    - unparam       # Find unused parameters
    - nakedret      # Detect naked returns
    - copyloopvar   # Check for pointer to loop variable
    - gosec         # Security checks
    - bodyclose     # Check HTTP response body is closed
    - noctx         # HTTP request without context
    - rowserrcheck  # Check sql.Rows.Err
    - sqlclosecheck # Check sql.DB is closed

  disable:
    - funlen
    - gocognit
    - nestif
    - godox
    - wsl
    - nlreturn
    - exhaustruct
    - varnamelen
    - ireturn

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 30
    staticcheck:
      checks: ["all"]

