# .goreleaser.yml 

before:
  hooks:
    # 不要 go mod tidy（会污染 workspace）
    - go generate ./...

# ---- Build Configuration ----
builds:
  - id: boba
    main: ./cmd/boba
    binary: boba
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64 # Windows ARM64 不稳定，跳过
    ldflags:
      - -s -w
      - -X github.com/royisme/BobaMixer/internal/version.Version={{ .Version }}
      - -X github.com/royisme/BobaMixer/internal/version.Commit={{ .Commit }}
      - -X github.com/royisme/BobaMixer/internal/version.Date={{ .Date }}
      - -X github.com/royisme/BobaMixer/internal/version.BuiltBy=goreleaser

# ---- Archives / Packaging ----
archives:
  - id: archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Target }}"
    # 模块化布局
    files:
      - README.md
      - LICENSE
      - configs/examples/**
    format_overrides:
      - goos: windows
        format: zip

# ---- Checksums ----
checksum:
  name_template: "checksums.txt"

# ---- Snapshot releases ----
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT"

# ---- Changelog ----
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "^perf:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

# ---- Homebrew Tap ----
brews:
  - repository:
      owner: royisme
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: boba
    homepage: "https://github.com/royisme/BobaMixer"
    description: "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
    license: MIT
    test: |
      system "#{bin}/boba version"
    # brew bottle 支持 (未来扩展)
    install: |
      bin.install "boba"
