version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: boba
    main: ./cmd/boba
    binary: boba
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/royisme/bobamixer/internal/version.Version={{.Version}}
      - -X github.com/royisme/bobamixer/internal/version.Commit={{.Commit}}
      - -X github.com/royisme/bobamixer/internal/version.Date={{.Date}}
      - -X github.com/royisme/bobamixer/internal/version.BuiltBy=goreleaser

archives:
  - id: default
    ids:
      - boba
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - configs/examples/**
    wrap_in_directory: false

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "^perf:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
    - title: Others

# GoReleaser v2 cask config (recommended for v2, handles macOS quarantine automatically)
homebrew_casks:
  - name: bobamixer
    directory: Casks
    homepage: "https://github.com/royisme/BobaMixer"
    description: "CLI tool for managing multiple AI providers with intelligent routing and cost tracking"
    license: MIT
    ids:
      - default
    repository:
      owner: royisme
      name: homebrew-tap
    commit_author:
      name: royisme
      email: imroybox@gmail.com

    # Helps pass homebrew audit
    url:
      verified: github.com/royisme/BobaMixer

    # Remove macOS quarantine attribute to avoid "unidentified developer" warnings
    # This is necessary because the binary isn't signed and notarized
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boba"]
          end
